server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  # Docker container logs
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag

  # Go application logs
  - job_name: scheduler
    static_configs:
    - targets:
        - localhost
      labels:
        job: scheduler
        app: training-scheduler
        component: scheduler
        __path__: /var/log/scheduler/*.log

  - job_name: worker
    static_configs:
    - targets:
        - localhost
      labels:
        job: worker
        app: training-scheduler
        component: worker
        __path__: /var/log/worker/*.log