{
 "title": "Worker Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "worker",
    "label": "Worker",
    "query": "label_values(worker_status, worker_id)"
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": "label_values(worker_gpu_utilization, gpu_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "worker_gpu_utilization{worker_id=~\"$worker\", gpu_id=~\"$gpu\"}",
     "legendFormat": "{{worker_id}} - GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "worker_gpu_memory_usage_mb{worker_id=~\"$worker\", gpu_id=~\"$gpu\"}",
     "legendFormat": "{{worker_id}} - GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Task Progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "worker_task_progress{worker_id=~\"$worker\"}",
     "legendFormat": "{{worker_id}} - {{task_name}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "Worker Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "worker_status{worker_id=~\"$worker\"}"
    }
   ]
  }
 ]
}