global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'scheduler'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'

  - job_name: 'workers'
    static_configs:
      - targets: ['host.docker.internal:9092']
    metrics_path: '/metrics'