apiVersion: 1

policies:
  - orgId: 1
    receiver: email-notifications
    group_by: ['alertname', 'severity']
    routes:
      - receiver: slack-critical
        matchers:
          - severity = critical
        continue: true
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
      - receiver: slack-warnings
        matchers:
          - severity = warning
        continue: true
        group_by: ['alertname']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    mute_timings: []